config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # get '/static', to: root_path

  resources :artists, only: %i[index show]
  resources :cards, only: %i[index show] do
    collection do
      get 'search'
    end
  end
  resources :colors, only: %i[index show]
  resources :rulings, only: %i[index show]

  # Catch-all
  resources :pages, only: :show
  get '/:permalink', to: 'pages#permalink', as: 'permalink'

  root to: 'cards#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
# frozen_string_literal: true

class Artist < ApplicationRecord
  has_many :cards

  validates :name, uniqueness: true
end

app/models/card.rb
# frozen_string_literal: true

class Card < ApplicationRecord
  belongs_to :artist
  belongs_to :color, optional: true

  has_many :card_rulings
  has_many :rulings, through: :card_rulings

  validates :name, :display_type, :power, :toughness, :rarity, presence: true
  validates :name, uniqueness: true
end

app/models/card_ruling.rb
class CardRuling < ApplicationRecord
  belongs_to :card
  belongs_to :ruling
end

app/models/color.rb
# frozen_string_literal: true

class Color < ApplicationRecord
  has_many :cards

  validates :name, uniqueness: true
end

app/models/page.rb
# frozen_string_literal: true

class Page < ApplicationRecord
  validates :title, :permalink, presence: true
  validates :permalink, uniqueness: true
end

app/models/ruling.rb
# frozen_string_literal: true

class Ruling < ApplicationRecord
  has_many :card_rulings
  has_many :cards, through: :card_rulings

  validates :title, :description, presence: true
  validates :title, :description, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artist = Artist.page(params[:page])
  end

  def show
    @artist = Artist.find(params[:id])
  end
end

app/controllers/cards_controller.rb
# frozen_string_literal: true

class CardsController < ApplicationController
  def index
    @card = Card.page(params[:page])
  end

  def show
    @card = Card.find(params[:id])
  end

  # GET /cards/search
  def search
    @query = params[:query]
    @all_cards = Card.where('name LIKE ?', "%#{@query}%")
    @card = @all_cards.page(params[:page])
  end
end

app/controllers/colors_controller.rb
# frozen_string_literal: true

class ColorsController < ApplicationController
  def index
    @color = Color.all
  end

  def show
    @color = Color.find(params[:id])
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  before_action :set_page, only: %i[show edit update destroy]

  # GET /static/:permalink
  def permalink
    @page = Page.find_by_permalink(params[:permalink])

    if @page
      render :show # /app/views/pages/show.html.erb
    else
      redirect_to root_path
    end
  end

  # GET /pages
  # GET /pages.json
  def index
    @pages = Page.all
  end

  # GET /pages/1
  # GET /pages/1.json
  def show; end

  # GET /pages/new
  def new
    @page = Page.new
  end

  # GET /pages/1/edit
  def edit; end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(page_params)

    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pages/1
  # PATCH/PUT /pages/1.json
  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_page
    @page = Page.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def page_params
    params.require(:page).permit(:title, :content, :permalink)
  end
end

app/controllers/rulings_controller.rb
class RulingsController < ApplicationController
  def index
    @ruling = Ruling.page(params[:page])
  end

  def show
    @ruling = Ruling.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/rulings_helper.rb
module RulingsHelper
end

app/views/artists/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Card Artists
    </h1>
    <% if @artist.empty? %>
      <p>There are no artists.</p>
    <% else %>
      <% @artist.each do |artist|%>
      <h2><%= link_to artist.name, artist %></h2>
      <% end %>
      <%= paginate @artist %>
    <% end %>
  </div>
</section>

app/views/artists/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-1 is-spaced">
      <%= @artist.name %>
    </h1>
    <div class="box">
      <h2 class="title is-2 is-spaced">
        Card List
      </h2>
      <ul>
        <% @artist.cards.each do |card| %>
          <li><%= link_to card.name, card %></li>
        <% end %>
      </ul>
    </div>
  </div>
</section>

app/views/cards/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Cards In Standard Format
    </h1>
    <% if @card.empty? %>
      <p>There are no cards.</p>
    <% else %>
      <% @card.each do |card|%>
      <h2><%= link_to card.name, card %></h2>
      <% end %>
      <%= paginate @card %>
    <% end %>
  </div>
</section>

app/views/cards/search.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Search Results
    </h1>
    <p>
      Your search for '<%= @query %>' returned <%= pluralize(@all_cards.size, 'result') %>.
    </p>
    <% @card.each do |card|%>
      <h2><%= link_to card.name, card %></h2>
    <% end %>
    <% if @all_cards.size > 0 %>
    <%= paginate @card %>
    <% end %>
  </div>
</section>

app/views/cards/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-1 is-spaced">
      <%= @card.name %>
    </h1>
    <div class="box">
      <h2 class="title is-2 is-spaced">
        Stats
      </h2>
      <ul>
        <li>Artist: <%= link_to @card.artist.name, @card.artist %></li>
        <li>Element: <%= link_to @card.color.name.capitalize, @card.color %> </li>
        <li>Converted Cost:
          <%= @card.converted_mana_cost %>
        </li>
        <li>Type: <%= @card.display_type %></li>
        <li>Stat Line: <%= @card.power %> / <%= @card.toughness %></li>
        <% unless @card.effect.nil? %>
          <li>Effect: <%= @card.effect %></li>
        <% end %>
      </ul>
    </div>
    <div class="box">
      <h2 class="title is-2 is-spaced">
        Flavor
      </h2>
      <ul>
        <li>Rarity: <%= @card.rarity %></li>
        <li>Flavor Text: <%= @card.flavor_text %></li>
      </ul>
    </div>
    <% unless @card.rulings.empty? %>
      <div class="box">
        <h2 class="title is-2 is-spaced">
          Rulings
        </h2>
        <ul>
          <% @card.rulings.each do |rule|%>
            <li><%= link_to rule.title, rule %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
</section>

app/views/colors/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Element Types
    </h1>
    <% if @color.empty? %>
      <p>There are no elements.</p>
    <% else %>
      <% @color.each do |e|%>
      <h2><%= link_to e.name.capitalize, e %></h2>
      <% end %>
    <% end %>
  </div>
</section>

app/views/colors/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-1 is-spaced">
      <%= @color.name.capitalize %>
    </h1>
    <div class="box">
      <h2 class="title is-2 is-spaced">
        Card List
      </h2>
      <ul>
        <% @color.cards.each do |card| %>
          <li><%= link_to card.name, card %></li>
        <% end %>
      </ul>
    </div>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>MTGJSON Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

<nav class="navbar" role="navigation" aria-label="main navigation">
  <div id="navbar" class="navbar-menu is-active">
    <div class="navbar-start">
      <%= link_to 'MTGJSON Project', root_path, :class => "navbar-item" %>

      <%= link_to 'About', permalink_path(permalink: 'about'), :class => "navbar-item" %>

      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          Data
        </a>

        <div class="navbar-dropdown">
          <%= link_to 'Card', cards_path, :class => "navbar-item" %>
          <%= link_to 'Element Types', colors_path, :class => "navbar-item" %>
          <%= link_to 'Artists', artists_path, :class => "navbar-item" %>
          <%= link_to 'Rulings', rulings_path, :class => "navbar-item" %>
        </div>
      </div>
    </div>

    <div class="navbar-end">
      <%= form_with(url: search_cards_path, method: "get", local: true, class: "navbar-item") do %>
        <%= text_field_tag(:query, nil, class: "input", placeholder: "Search Cards") %>
        <%= submit_tag("Search", :class => "button is-primary") %>
      <% end %>
    </div>
  </div>
</nav>

  <section class="section">
    <div class="container">
      <%= yield %>
    </div>
  </section>
</html>

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :permalink %>
    <%= form.text_field :permalink %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Permalink</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.content %></td>
        <td><%= page.permalink %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">
  <%= @page.title %>
</h1>

<p>
  <%= @page.content %>
</p>

app/views/rulings/index.html.erb
<section class="section">
  <div class="container">
    <h1 class="title">
      Card Rulings
    </h1>
    <% if @ruling.empty? %>
      <p>There are no rulings.</p>
    <% else %>
      <% @ruling.each do |e|%>
      <h2><%= link_to e.title, e %></h2>
      <% end %>
    <% end %>
  </div>
</section>

app/views/rulings/show.html.erb
<section class="section">
  <div class="container">
    <h1 class="title is-1 is-spaced">
      <%= @ruling.title %>
    </h1>
     <div class="box">
      <h2 class="title is-2 is-spaced">
        Ruling
      </h2>
      <ul>
          <li><%= @ruling.description %></li>
      </ul>
    </div>
    <div class="box">
      <h2 class="title is-2 is-spaced">
        Card List
      </h2>
      <ul>
        <% @ruling.cards.each do |card| %>
          <li><%= link_to card.name, card %></li>
        <% end %>
      </ul>
    </div>
  </div>
</section>